#!/usr/bin/env bash
# This script configures the http response saying which server is serving.
apt-get -y update
apt-get -y install nginx
sed -i '/^server_name _; {$/a \ \tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
