#!/usr/bin/env bash
# This script configures the load balancer.
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.8 -y
apt-get update -y
apt-get install haproxy=1.8.\* -y
echo "backend web-backend
        balance roundrobin
        server 507821-web-01 52.87.211.200:80 check
        server 507821-web-02 34.229.69.61:80 check

frontend http
        bind *:80
        mode http
        default_backend web-backend" >> /etc/haproxy/haproxy.cfg
service haproxy restart
