#!/usr/bin/env bash
# This script configures the http response saying which server is serving.
apt-get -y update
apt-get -y install nginx
sed -ie "s/^server_name _; {$/server_name _; \n\tadd_header X-Served-By \$hostname;/g" /etc/nginx/sites-available/default
service nginx restart
