#!/usr/bin/env bash
# print "Best School" 10 times and Hi at 9
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 10 ];then
    echo "Hi"
    fi
    echo "Best School"
    ((counter++))
done
